### ISSUE TITLE
eQTL-Expression summary

### ISSUE THREAD

**Issue by daniaki** [populationgenomics/exome-results-browsers#46] opened 2022-01-20 23:35 UTC
As a user, I would like to see a violin plot where the x-axis markers are the genotypes and the y-axis represents gene expression, so that I can visualise how the genotypes of an eQTL affect the expression distribution of a gene in a specific cell type.

**Comment by lgruen** [comment] 2022-01-21 01:20
Duplicate of #41.

**Closed as completed by lgruen** 2022-01-21 01:20 UTC
Labels: duplicate
